### ISSUE TITLE
After upgrading from 4.0.1 to 5.3.1, time_ago_in_words(b.updated_at, vague: true) no longer works

### ISSUE THREAD

**Issue by MSCAU** [radar/distance_of_time_in_words#125] opened 2021-06-15 10:28 UTC
I had to upgrade to Rails 5.2.6 yesterday to get around the MimeMagic license issue (see https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1). As the same time, dotiw got switched from 4.0.1 to 5.3.1. I now get this error which wan't present before:

`Unknown key: :vague. Valid keys are: :words_connector, :two_words_connector, :last_word_connector, :locale`

The line where this breaks reads:

`time_ago_in_words(b.updated_at, vague: true)`

Has something broken with this version change? I can't see anything in your docs or issues. If I amend the Gemfile to use 4.0.1 and `bundle update` again, the problem goes away.

**Comment by dblock** [comment] 2021-06-15 13:57
This sounds vaguely (no pun intended) familiar. I suspect that you're no longer calling this library, but the original Rails `time_ago_in_words` method. In which class is this call made?


1. Check that https://github.com/radar/distance_of_time_in_words/blob/master/lib/dotiw/action_view/helpers/date_helper.rb gets included in the location of the call. This should be automatic for wherever the method is available in Rails.
2. Check that it's calling the wrapped method, https://github.com/radar/distance_of_time_in_words/blob/1fea369b98044d71525fa16fd7a58f8cb24f8bc1/lib/dotiw/methods.rb#L38

**Comment by mozcomp** [comment] 2021-06-16 04:01
I'm getting a similar issue, though still with Rails 4.2.11, between DOTIW 4.0.1 -> 5.3.1

From the console ...

` helper.distance_of_time_in_words(Time.current, contract.expires_on, vague: true)
Traceback (most recent call last):
       15: from bin/rails:4:in `<main>'
       14: from bin/rails:4:in `require'
       13: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
       12: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
       11: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:68:in `console'
       10: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/console.rb:9:in `start'
        9: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/console.rb:110:in `start'
        8: from (irb):7
        7: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/dotiw-5.3.1/lib/dotiw/action_view/helpers/date_helper.rb:14:in `distance_of_time_in_words'
        6: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/dotiw-5.3.1/lib/dotiw/methods.rb:35:in `distance_of_time_in_words'
        5: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/dotiw-5.3.1/lib/dotiw/methods.rb:105:in `_display_time_in_words'
        4: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/array/conversions.rb:60:in `to_sentence'
        3: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/state_machines-0.5.0/lib/state_machines/assertions.rb:16:in `assert_valid_keys'
        2: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/state_machines-0.5.0/lib/state_machines/assertions.rb:16:in `each_key'
        1: from /usr/local/var/rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/state_machines-0.5.0/lib/state_machines/assertions.rb:18:in `block in assert_valid_keys'
ArgumentError (Unknown key: :vague. Valid keys are: :words_connector, :two_words_connector, :last_word_connector, :locale)`

though error appears downstream in activesupport/to_sentence

**Comment by mozcomp** [comment] 2021-06-16 04:30
I think the issue has arisen from commit 20/11/2020 by joshuapinter ...

where previous code called the activesupport method with `if options.delete(:vague}`
the new version calls it with the vague option `if options[:vague]`

old ..
> return _distance_of_time_in_words(from_time, to_time, options) if options.delete(:vague)        DOTIW::Methods.distance_of_time_in_words(from_time, to_time, include_seconds_or_options, options)

new ..
> return _distance_of_time_in_words(from_time, to_time, options) if options[:vague]        DOTIW::Methods.distance_of_time_in_words(from_time, to_time, include_seconds_or_options, options.except(:vague))



I'd create a pull request but it's beyond my pay grade!!

**Comment by dblock** [comment] 2021-06-16 14:35
That's correct @mozcomp. Making a pull request is definitely not above your pay grade though, we pay you enough :) 

Maybe try to write a spec that reproduces this [here](https://github.com/radar/distance_of_time_in_words/blob/master/spec/lib/dotiw_spec.rb#L420)? The code fix is trivial, we need to do `options = options.except(:vague)` somewhere in this code.

**Comment by MSCAU** [comment] 2021-06-20 00:27
> This sounds vaguely (no pun intended) familiar. I suspect that you're no longer calling this library, but the original Rails `time_ago_in_words` method. In which class is this call made?
> 
> 1. Check that https://github.com/radar/distance_of_time_in_words/blob/master/lib/dotiw/action_view/helpers/date_helper.rb gets included in the location of the call. This should be automatic for wherever the method is available in Rails.
> 2. Check that it's calling the wrapped method, https://github.com/radar/distance_of_time_in_words/blob/1fea369b98044d71525fa16fd7a58f8cb24f8bc1/lib/dotiw/methods.rb#L38

Sorry, my Rails is very rusty and I don't remember enough to understand your questions.

I am making the call thus, in a file called app/views/budgets/browse.jb, which uses https://github.com/amatsuda/jb:

```
def budget(b)

	json = {
		id: b.id,
		name: b.name,
		time: time_ago_in_words(b.updated_at, vague: true),
		owner: {
                   ...
```

**Comment by matt-whiteley** [comment] 2021-11-08 18:15
Would it be possible to get a new release now that a fix has been merged? The latest on RubyGems is the version with this bug present.

I don't like tracking `master` in production deployed code!

Thanks!

**Comment by dblock** [comment] 2021-11-08 19:39
This was fixed in https://github.com/radar/distance_of_time_in_words/pull/126

**Closed by dblock** 2021-11-08 19:39 UTC
Labels: bug?

**Comment by dblock** [comment] 2021-11-08 19:41
@matt-whiteley Done.
